from __future__ import annotations

import pandas as pd


UNASSIGNED_LT_DATE = pd.Timestamp("2099-07-04")
UNASSIGNED_LT_FALLBACK_DATE = pd.Timestamp("2099-12-31")
INVALID_SUPPLY_DATE_START = pd.Timestamp("2099-01-01")
SHORTAGE_REPORT_CUTOFF = pd.Timestamp("2026-12-31")

UNASSIGNED_LT_DATES = frozenset({UNASSIGNED_LT_DATE, UNASSIGNED_LT_FALLBACK_DATE})
DUMMY_SHIP_DATES = UNASSIGNED_LT_DATES
